# Generated by Django 4.2.6 on 2023-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
