# Generated by Django 4.2.6 on 2023-10-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_likeditem_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeditem',
            name='text',
        ),
    ]
