# Generated by Django 4.2.6 on 2023-11-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desccription',
            new_name='description',
        ),
    ]
